cart/urls.py
from django.urls import path, include
from . import views

app_name='cart'

urlpatterns = [
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail'),
]

redpandasushi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('', include('shop.urls', namespace='shop')),
    path('menu/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, include
from . import views

app_name='shop'

urlpatterns=[
    path('',views.product_list, name='product_list'),
    path('menu/',views.menu, name='menu'),
    path('delivery/',views.delivery, name='delivery'),
    path('news/',views.news, name='news'),
    path('cart/', include('cart.urls')),
    path('<int:id>/<slug:slug>/',views.product_detail,name='product_detail'),
    path('news/<int:id>/<slug:slug>/',views.news_detail, name='news_detail'),
    path('<str:category_slug>/',views.product_list, name='product_list_by_category'),
    path('<str:category_slug>/<str:filtering>/',views.product_list, name='product_list_by_category'),
]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True,verbose_name='Название категории')
    slug = models.SlugField(max_length=200, db_index=True, unique=True,verbose_name='Название страницы')
    image = models.FileField(upload_to='category/', blank=True,verbose_name='Маленькая картинка для бокового меню(svg)')
    image_big = models.FileField(upload_to='category/', blank=True,verbose_name='Большая картинка для меню')
    order_id = models.IntegerField(verbose_name='Порядок в меню',unique=True, null=True)

    class Meta:
        ordering = ('order_id',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug])
            
    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products' , on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, db_index=True, verbose_name='Сcылка в поисковой строке транслитом')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name='Картинка')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    available = models.BooleanField(default=True, verbose_name='Наличие')
    drink = models.BooleanField(default=False, verbose_name='Напиток')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено')

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def get_absolute_url(self):
        return reverse('shop:product_detail',args=[self.id, self.slug])

    def __str__(self):
        return self.name

class Articles(models.Model):
    title = models.CharField(max_length=200, db_index=True)
    subtitle = models.CharField(max_length=200,verbose_name='Подзаголовок статьи',null=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='articles/', blank=True)
    text = models.TextField(verbose_name='Текст статьи')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    
    class Meta:
        ordering = ('id',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
    
    def get_absolute_url(self):
        return reverse('shop:news_detail',args=[self.id, self.slug])

    def __str__(self):
        return self.title

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product, Category
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    categories= Category.objects.all()
    return render(request, 'cart/detail.html', {'cart': cart,'categories':categories})

shop/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from .models import Category, Product, Articles
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from cart.forms import CartAddProductForm

# Create your views here.

def index(request):
    return render(request, 'shop/product/index.html')

def product_list(request,category_slug=None,filtering=None):
    category = None
    categories= Category.objects.all()
    products = Product.objects.filter(available=True)
    cart_product_form = CartAddProductForm()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    if filtering:
        products = products.order_by('-'+filtering)
    paginator = Paginator(products, 2)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)


    return render(request,'shop/product/index.html',{'category': category,'categories': categories,'products': products, 'page': page,'posts': posts,'cart_product_form': cart_product_form})

def menu(request):
    categories= Category.objects.all()
    return render(request,'shop/product/menu.html',{'categories': categories})

def delivery(request):
    categories= Category.objects.all()
    return render(request,'shop/product/delivery.html',{'categories': categories})

def news(request):
    categories= Category.objects.all()
    articles= Articles.objects.all()
    return render(request,'shop/product/news.html',{'articles': articles,'categories': categories})

def news_detail(request,id,slug):
    categories= Category.objects.all()
    news = get_object_or_404(Articles,id=id,slug=slug)
    return render(request, 'shop/product/news_detail.html', {'article': news,'categories': categories})


def product_detail(request,id,slug):
    categories= Category.objects.all()
    product = get_object_or_404(Product,id=id,slug=slug,available=True)
    drink = Product.objects.filter(drink=True)
    eat = Product.objects.filter(drink=False)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,'categories': categories,'cart_product_form': cart_product_form, 'napitki':drink, 'eat': eat})

def cart_gen(request):
    categories= Category.objects.all()
    products = Product.objects.filter(available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/cart.html', {'product': products,'categories': categories,'cart_product_form': cart_product_form})

cart/templates/cart/detail.html
{% load static %}
{% for item in cart %}
        {% with product=item.product %}
        <div class="main-offer_list-item">
            <div class="main-offer_list-info">
                <div class="main-offer_list-title">
                    {{ product.name }}
                </div>
                <div class="main-offer_list-calc">
                    {{item.quantity}}
                </div>
            </div>
            <img src="{{ product.image.url }}" alt="">
            <div class="main-offer_list-close">
                <a class="delete-btn" data-delete="{% url 'cart:cart_remove' product.id %}"><img class="img-svg" src="{% static 'img/close.svg' %}" alt=""></a>
            </div>
        </div>
        {% endwith %}
{% endfor %}
<input type="hidden" name="cart_price" value="{{ cart.get_total_price }}">

shop/templates/shop/product/cart.html
{% load static %}
{% for item in cart %}
        {% with product=item.product %}
        <div class="main-offer_list-item">
            <div class="main-offer_list-info">
                <div class="main-offer_list-title">
                    {{ product.name }}
                </div>
                <div class="main-offer_list-calc">
                    {{item.quantity}}
                </div>
            </div>
            <img src="{{ product.image.url }}" alt="">
            <div class="main-offer_list-close">
                <a class="delete-btn" data-delete="{% url 'cart:cart_remove' product.id %}"><img class="img-svg" src="{% static 'img/close.svg' %}" alt=""></a>
            </div>
        </div>
        {% endwith %}
{% endfor %}
<input type="hidden" name="cart_price" value="{{ cart.get_total_price }}">

shop/templates/shop/product/delivery.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Доставка
{% endblock %}
{% block content %}
<div class="main-content main-content_deliveryFlex">
    <div class="main-content_left">
        <div class="main-content_title">
            Доставка
        </div>
        <div class="main-content_delivery">
            <div class="main-content_delivery-subtitle">

            </div>
            <div class="main-content_delivery-title">
                Как сделать заказ
            </div>
            <div class="main-content_delivery-block">
                <div class="main-content_delivery-block_item">
                    <img class="img-svg" src="{% static 'img/search.svg'%}" alt="">
                    <div class="main-content_delivery-block_text">
                        На сайте
                    </div>
                </div>
                <div class="main-content_delivery-block_item">
                    <img class="img-svg" src="{% static 'img/phone-delivery.svg'%}" alt="">
                    <div class="main-content_delivery-block_text">
                        По телефону
                    </div>
                </div>
            </div>
            <div class="main-content_delivery-title">
                Оплата
            </div>
            <div class="main-content_delivery-block">
                <div class="main-content_delivery-block_item">
                    <img class="img-svg" src="{% static 'img/delivery.svg'%}" alt="">
                    <div class="main-content_delivery-block_text">
                        Наличными курьеру
                    </div>
                </div>
                <div class="main-content_delivery-block_item">
                    <img class="img-svg" src="{% static 'img/credit-card.svg'%}" alt="">
                    <div class="main-content_delivery-block_text">
                        Оплата картой
                    </div>
                </div>
            </div>
            <div class="main-content_delivery-title">
                Как получить заказ
            </div>
            <div class="main-content_delivery-block">
                <div class="main-content_delivery-block_item">
                    <img class="img-svg" src="{% static 'img/food-delivery.svg'%}" alt="">
                    <div class="main-content_delivery-block_text">
                        Доставка курьером
                    </div>
                </div>
                <div class="main-content_delivery-block_item">
                    <img class="img-svg" src="{% static 'img/salesman.svg'%}" alt="">
                    <div class="main-content_delivery-block_text">
                        Предзаказ на указанное время 
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="main-content_right">
        <div class="main-content_right-title">
            К заказам, в зависимости от количества суши и роллов, бесплатно прилагается порция имбиря, а также палочки на выбор (учебные или обычные), соевый соус и васаби по количеству приборов.
        </div>
    </div>
</div>
{% endblock %}

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if product %}{{ product.name }}{% else %}Red Panda Sushi{% endif %}
{% endblock %}

{% block content %}
<div class="main-content">
    <div class="main-content_card">
        <div class="main-content_card-block">
            <div class="main-content_card-img">
                <img src="{{ product.image.url }}" alt="">
            </div>
            <div class="main-content_card-info">
                <span class="main-content_card-info_title">
                    {{ product.name }}
                </span>
                <div class="main-content_card-info_weight">
                    Вес: <span>320 г.</span>
                </div>
                <div class="main-content_card-info_make">
                    {{product.description}}
                </div>
                <div class="main-content_card-info_buy">
                    <div class="main-content_card-info_price">
                        {{ product.price }} грн. <span class="main-content_card-info-gram">320 г</span>
                    </div>
                    <form class="add_to_cart" data-action="{% url 'cart:cart_add' product.id %}" method="post">
                        {{ cart_product_form }}
                        {% csrf_token %}
                        <button class="main-content_block-item_btn" type="submit">
                            В корзину
                        </button>
                    </form>
                </div>
                <div class="main-content_card-info_delivery">
                    <img class="img-svg" src="img/delivery.svg" alt="">
                    <span>
                        Бесплатная доставка при заказе на сумму от 350 грн.
                    </span>
                </div>
            </div>
        </div>
        <div class="main-content_card-recomendation">
            <div class="main-content_card-recomendation_drink">
                <div class="main-content_card-recomendation_drink-title">
                    Рекомендуем напитки к данному блюду:
                </div>
                <div class="main-content_card-recomendation_drink-slider">
                    {% for d in napitki %}
                    <div class="main-content_card-recomendation_drink-slider_item">
                        <div class="main-content_block-item">
                            <img src="{{d.image.url}}" alt="">
                            <div class="main-content_block-item_title">
                                <span class="main-content_block-item_title-main">
                                    {{ d.name }}
                                </span>
        
                                <span class="main-content_block-item_title-span">
                                    320 г
                                </span>
                            </div>
                            <div class="main-content_block-item_make">
                                {{d.description}}
                            </div>
                            <div class="main-content_block-item_buy">
                                <div class="main-content_block-item_price">
                                    {{d.price}} грн. <span class="main-content_block-item_price-gram">320 г</span>
                                </div>
                                <form class="add_to_cart" data-action="{% url 'cart:cart_add' d.id %}" method="post">
                                    {{ cart_product_form }}
                                    {% csrf_token %}
                                    <button class="main-content_block-item_btn" type="submit">
                                        В корзину
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="main-content_card-recomendation">
            <div class="main-content_card-recomendation_snacks">
                <div class="main-content_card-recomendation_snacks-title">
                    Рекомендуем попробовать:
                </div>
                <div class="main-content_card-recomendation_snacks-slider">
                    {% for d in eat %}
                    <div class="main-content_card-recomendation_drink-slider_item">
                        <div class="main-content_block-item">
                            <img src="{{d.image.url}}" alt="">
                            <div class="main-content_block-item_title">
                                <span class="main-content_block-item_title-main">
                                    {{d.name}}
                                </span>
        
                                <span class="main-content_block-item_title-span">
                                    320 г
                                </span>
                            </div>
                            <div class="main-content_block-item_make">
                                {{d.description}}
                            </div>
                            <div class="main-content_block-item_buy">
                                <div class="main-content_block-item_price">
                                    {{d.price}} грн. <span class="main-content_block-item_price-gram">320 г</span>
                                </div>
                                <form class="add_to_cart" data-action="{% url 'cart:cart_add' d.id %}" method="post">
                                    {{ cart_product_form }}
                                    {% csrf_token %}
                                    <button class="main-content_block-item_btn" type="submit">
                                        В корзину
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

shop/templates/shop/product/index.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Red Panda Sushi{% endif %}
{% endblock %}

{% block content %}
<div class="main-content">
    <div class="main-content_title">
        {% if category %}{{ category.name }}{% else %}Наша продукция{% endif %}
    </div>
    <div id="main" class="main-content_block">
        {% for product in posts %}
        <div class="main-content_block-item">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="">
            <div class="main-content_block-item_title">
                <span class="main-content_block-item_title-main">
                    <a href="{{product.get_absolute_url}}">{{ product.name }}</a>
                </span>

                <span class="main-content_block-item_title-span">
                    320 г
                </span>
            </div>
            <div class="main-content_block-item_make">
                {{product.description}}
            </div>
            <div class="main-content_block-item_buy">
                <div class="main-content_block-item_price">
                    ₴{{ product.price }} <span class="main-content_block-item_price-gram">320 г</span>
                </div>
                <form class="add_to_cart" data-action="{% url 'cart:cart_add' product.id %}" method="post">
                    {{ cart_product_form }}
                    {% csrf_token %}
                    <button class="main-content_block-item_btn" type="submit">
                        В корзину
                    </button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    {% include "shop/product/pagination.html" with page=posts %}
</div>
{% endblock %}

shop/templates/shop/product/menu.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Меню{% endif %}
{% endblock %}
{% block content %}
<div class="main-content">
            <div class="main-content_title">
                Меню
            </div>
            <div class="main-content_menu">
            {% for c in categories %}
                <div class="main-content_menu-item">
                    <a href="{{c.get_absolute_url}}">
                        <img src="{{c.image_big.url}}" alt="">
                        <div class="main-content_menu-item_title">
                            {{c.name}}
                        </div>
                    </a>
                </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

shop/templates/shop/product/news.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Новости и акции
{% endblock %}
{% block content %}
<div class="main-content">
<div class="main-content_title">
    Новости и акции
</div>
<div class="main-content_news">
{% for c in articles %}
    <div class="main-content_news-item">
        <img src="{{c.image.url}}" alt="">
        <div class="main-content_news-item_date">
            {{c.created}}
        </div>
        <div class="main-content_news-item_title">
            <a href="{{c.get_absolute_url}}">
                {{c.title}}
            </a>
        </div>
        <div class="main-content_news-item_desc">
            {{c.text}}
        </div>
    </div>
{% endfor %}
</div>
</div>
{% endblock %}

shop/templates/shop/product/news_detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if article %}{{ article.title }}{% else %}Новости{% endif %}
{% endblock %}
{% block content %}
<div class="main-content">
        <div class="main-content_newsCard">
            <div class="main-content_newsCard-title">
                {{ article.title }}
            </div>
            <div class="main-content_newsCard-block">
                <img class="img-svg" src="{{ article.image.url }}" alt="">
                <div class="main-content_newsCard-block_item">
                    <div class="main-content_newsCard-block_title">
                        {{ article.title }}  
                    </div>
                    <div class="main-content_newsCard-block_subtitle">
                        {% if article.subtitle %}{{ article.subtitle }}{% else %}{% endif %}
                    </div>
                    <ul class="main-content_newsCard-block_list">
                        <li>- Атлантика</li>
                        <li>- Американо</li>
                        <li>- Поло</li>
                    </ul>
                    <div class="main-content_newsCard-block_text">
                        {{article.text}}
                    </div>
                    <a href="#" class="main-content_newsCard-block_back">
                        <img class="img-svg" src="{% static 'img/arrows.svg' %}" alt="">
                        <span>
                            Вернуться к остальным новостям
                        </span>
                    </a>
                </div>
            </div>
</div>
{% endblock %}

shop/templates/shop/product/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>